SE-GOAT/jpetstore

src/main/java/org/mybatis/jpetstore/domain/Account.java
=> feat(jpetStore) : 어떤 기능 추가 연습

.idea/compiler.xml, .idea/dataSources.xml, pom.xml, src/main/java/org/mybatis/jpetstore/domain/Account.java, src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java, src/main/java/org/mybatis/jpetstore/mapper/ProductMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/AccountMapper.xml, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml, src/main/resources/org/mybatis/jpetstore/mapper/ProductMapper.xml, src/main/webapp/WEB-INF/jsp/account/SignonForm.jsp, src/main/webapp/WEB-INF/jsp/catalog/ProductByAdmin.jsp, src/main/webapp/WEB-INF/jsp/common/IncludeTop.jsp, target/classes/org/mybatis/jpetstore/mapper/AccountMapper.xml, target/classes/org/mybatis/jpetstore/mapper/ItemMapper.xml, target/classes/org/mybatis/jpetstore/mapper/ProductMapper.xml, target/jpetstore/META-INF/MANIFEST.MF, target/jpetstore/WEB-INF/classes/org/mybatis/jpetstore/mapper/AccountMapper.xml, target/jpetstore/WEB-INF/classes/org/mybatis/jpetstore/mapper/ItemMapper.xml, target/jpetstore/WEB-INF/classes/org/mybatis/jpetstore/mapper/ProductMapper.xml, target/jpetstore/WEB-INF/jsp/account/SignonForm.jsp, target/jpetstore/WEB-INF/jsp/catalog/ProductByAdmin.jsp, target/jpetstore/WEB-INF/jsp/common/IncludeTop.jsp
=> chore: itemList xml 수정

.idea/dataSources.xml, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/application.properties, src/main/webapp/WEB-INF/jsp/catalog/ItemByAdmin.jsp, src/main/webapp/WEB-INF/jsp/catalog/Product.jsp, src/main/webapp/WEB-INF/jsp/catalog/ProductByAdmin.jsp, target/classes/application.properties, target/classes/org/mybatis/jpetstore/mapper/ItemMapper.xml, target/jpetstore/WEB-INF/classes/application.properties, target/jpetstore/WEB-INF/classes/org/mybatis/jpetstore/mapper/ItemMapper.xml, target/jpetstore/WEB-INF/jsp/catalog/ItemByAdmin.jsp, target/jpetstore/WEB-INF/jsp/catalog/Product.jsp, target/jpetstore/WEB-INF/jsp/catalog/ProductByAdmin.jsp
=> feat: product edit화면 추가

pom.xml, src/main/webapp/WEB-INF/jsp/account/SignonForm.jsp, src/main/webapp/WEB-INF/jsp/common/IncludeTop.jsp
=> feat: admin판별 추가

src/main/java/org/mybatis/jpetstore/domain/AnimalInfo.java, src/main/java/org/mybatis/jpetstore/domain/EnvironmentByUser.java, src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml, src/main/webapp/WEB-INF/jsp/catalog/Category.jsp, src/main/webapp/WEB-INF/jsp/catalog/Item.jsp, src/main/webapp/WEB-INF/jsp/catalog/Product.jsp
=> feat: 동물 정보 표 추가

src/main/java/org/mybatis/jpetstore/domain/Item.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml, src/main/webapp/WEB-INF/jsp/catalog/Item.jsp
chore: 카테고리 아이디 불러오기 수정 
추가 사항: 불필요한 jsp 코드 삭제
=> chore: 카테고리 아이디 불러오기 수정 

src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml
chore: 테이블 변경으로 인한 정보테이블 조회 쿼리문 수정
=> chore: 테이블 변경으로 인한 정보테이블 조회 쿼리문 수정

src/main/webapp/WEB-INF/jsp/catalog/Item.jsp
동물에 대한 정보가 없거나 사용자가 환경에 대한 정보를 입력하지 않은 경우, 안내문이 출력되도록 Item.jsp 수정
=> fix: 환경 테이블 및 정보 테이블에 대한 예외처리

src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/webapp/WEB-INF/jsp/catalog/ItemListByAdmin.jsp, src/main/webapp/WEB-INF/jsp/catalog/SettingItemByAdmin.jsp, src/main/webapp/WEB-INF/jsp/common/AccessRestriction.jsp
=> fix: 페이지 관리자 인증 수정

src/main/java/org/mybatis/jpetstore/domain/AnimalInfo.java, src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml, src/main/resources/org/mybatis/jpetstore/mapper/ProductMapper.xml, src/main/webapp/WEB-INF/jsp/catalog/Item.jsp, src/main/webapp/WEB-INF/jsp/catalog/ItemListByAdmin.jsp, src/main/webapp/WEB-INF/jsp/catalog/ProductListByAdmin.jsp, src/main/webapp/WEB-INF/jsp/catalog/SettingItemByAdmin.jsp, src/main/webapp/WEB-INF/jsp/catalog/UpdateAnimalInfoFormByAdmin.jsp
=> refactor: 화면 구성 수정

src/main/java/org/mybatis/jpetstore/domain/AnimalInfo.java, src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml, src/main/webapp/WEB-INF/jsp/catalog/InsertAnimalInfoByAdmin.jsp, src/main/webapp/WEB-INF/jsp/catalog/SettingItemByAdmin.jsp, src/main/webapp/WEB-INF/web.xml
=> feat: 기준 추가 완료 & 기준 삭제 진행중

src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml, src/main/webapp/WEB-INF/jsp/catalog/SettingItemByAdmin.jsp
=> fix: jsp 연결 링크 수정

src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java, src/main/java/org/mybatis/jpetstore/mapper/ProductMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml, src/main/resources/org/mybatis/jpetstore/mapper/ProductMapper.xml, src/main/webapp/WEB-INF/jsp/catalog/InsertAnimalInfoByAdmin.jsp
=> fix: 기준 추가 기능 구현 & 중복 검사 예정

src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml, src/main/webapp/WEB-INF/jsp/catalog/SettingItemByAdmin.jsp
=> feat: 기준 추가 시 중복성 검사 완료

src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java, src/main/java/org/mybatis/jpetstore/mapper/ProductMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml, src/main/resources/org/mybatis/jpetstore/mapper/ProductMapper.xml, src/main/webapp/WEB-INF/jsp/catalog/SettingItemByAdmin.jsp
fix: 기준 중복성 검사 완료 & animal info 완료
=> fix: 기준 중복성 검사 완료 & animal info 완료

src/main/java/org/mybatis/jpetstore/mapper/EnvironmentMapper.java, src/main/java/org/mybatis/jpetstore/mapper/ProductMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ProductMapper.xml, src/main/webapp/WEB-INF/jsp/catalog/InsertProductByAdmin.jsp, src/main/webapp/WEB-INF/jsp/catalog/ProductListByAdmin.jsp
=> feat: add product 완료

src/main/resources/org/mybatis/jpetstore/mapper/EnvironmentMapper.xml
=> chore: order by 추가

src/main/webapp/WEB-INF/jsp/catalog/SettingUserEnvForm.jsp, src/main/webapp/WEB-INF/jsp/catalog/UpdateUserEnvValueForm.jsp
fix: 되돌아가기 버튼 후 categoryId 넘겨주기 완료
=> fix: 되돌아가기 버튼 후 categoryId 넘겨주기 완료

src/main/resources/org/mybatis/jpetstore/mapper/EnvironmentMapper.xml
=> fix: Environment query 수정

src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml
=> feat: add product시 db 추가

src/main/java/org/mybatis/jpetstore/domain/AnimalInfo.java, src/main/java/org/mybatis/jpetstore/mapper/ItemMapper.java, src/main/java/org/mybatis/jpetstore/service/CatalogService.java, src/main/java/org/mybatis/jpetstore/web/actions/CatalogActionBean.java, src/main/resources/org/mybatis/jpetstore/mapper/ItemMapper.xml, src/main/webapp/WEB-INF/jsp/catalog/ItemListByAdmin.jsp
=> fix: delete & add 수정
